### PR TITLE
Uplift third_party/tt-mlir to origin/main 2024-11-07

### PR DESCRIPTION
**Pull request by vmilosevic**
This PR uplifts the third_party/tt-mlir submodule to the origin/main

### CODE REVIEW

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Comment by nvukobratTT** [comment]
@vmilosevic seems like the build failed here. From what I see, this seems to be the build issue:
image

@svuckovicTT do you have more context around this one?

**Comment by nvukobratTT** [comment]
@vmilosevic even after this build error, the rest of the stages seem to continue running. Is this expected?

**Comment by svuckovicTT** [comment]
> @vmilosevic seems like the build failed here. From what I see, this seems to be the build issue: image
> 
> @svuckovicTT do you have more context around this one?

I know what the issue is, but not sure what the fix is. @rpavlovicTT has looked into this, he can help

**Comment by rpavlovicTT** [comment]
> > @vmilosevic seems like the build failed here. From what I see, this seems to be the build issue: image
> > @svuckovicTT do you have more context around this one?
> 
> I know what the issue is, but not sure what the fix is. @rpavlovicTT has looked into this, he can help

Latest llvm version changed emitC dialect, and @mtopalovicTT had to change how we create some ops accordingly. Here the problem is probably that toolchain is not updated. What's the llvm commit we are running against?

**Review by nvukobratTT — APPROVED** [review]

**Comment by nvukobratTT** [comment]
> > > @vmilosevic seems like the build failed here. From what I see, this seems to be the build issue: image
> > > @svuckovicTT do you have more context around this one?
> > 
> > 
> > I know what the issue is, but not sure what the fix is. @rpavlovicTT has looked into this, he can help
> 
> Latest llvm version changed emitC dialect, and @mtopalovicTT had to change how we create some ops accordingly. Here the problem is probably that toolchain is not updated. What's the llvm commit we are running against?

@vmilosevic can you provide more details? :)) Do we need to update our containers?

**Comment by vmilosevic** [comment]
Yes, there was an LLVM change in mlir that case incompatibility with old toolchain, this is probably the same thing.
We can do it manually, but I'm also making a change in docker build to be a part of a workflow (see https://github.com/tenstorrent/tt-mlir/pull/928#pullrequestreview-2375280337) so you can also wait untill I do the similar change on tt-forge-fe

**Comment by nvukobratTT** [comment]
> Yes, there was an LLVM change in mlir that case incompatibility with old toolchain, this is probably the same thing. We can do it manually, but I'm also making a change in docker build to be a part of a workflow (see [tenstorrent/tt-mlir#928 (review)](https://github.com/tenstorrent/tt-mlir/pull/928#pullrequestreview-2375280337)) so you can also wait untill I do the similar change on tt-forge-fe

Thanks! Let me know if this will take a bit longer. In that case, we should push this manually. If you expect changes to land during next week, we can wait a bit :))

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Review by nvukobratTT — APPROVED** [review]

**Pull request merged**
