### PR TITLE
Uplift third_party/tt-mlir to origin/main 2024-10-03

### PR DESCRIPTION
**Pull request by vmilosevic**
This PR uplifts the third_party/tt-mlir submodule to the origin/main

### CODE REVIEW

**Review by nvukobratTT — APPROVED** [review]

**Comment by nvukobratTT** [comment]
Auto-approve works, but this PR got merged before we got confirmation that all tests are passing. 

Let's fix it before next one, or disable it until we figure out what happend

**Comment by vmilosevic** [comment]
Lets try configuring tests as required to pass in project settings

**Comment by vmilosevic** [comment]
I added these two to be required
image
It looks like that checks are still running, we will monitor and revert this uplift if they fail.

**Comment by pilkicTT** [comment]
Also, I think we silently transitioned to using `squash and merge` for merging PRs, so this one should also use that instead of creating a merge commit (we should probably set this globally in repo settings)

**Pull request merged**
