### PR TITLE
adding community workflow for issues

### PR DESCRIPTION
**Pull request by staylorTT**
Adding a workflow to send a slack message to the tt-forge-fe-code-changes channel when a community issue is filed.

### CODE REVIEW

**Comment by staylorTT** [comment]
Once we merge this I will file an issue / PR from a non TT GH account to validate that it's working

**Review by nvukobratTT — COMMENTED** [review]
Looks good, important part from my end is that we're also labeling community issues on GitHub, besides sending a message :))

I'll leave for more detailed overview to @vmilosevic

**Comment by staylorTT** [comment]
> Looks good, important part from my end is that we're also labeling community issues on GitHub, besides sending a message :))
> 
> I'll leave for more detailed overview to @vmilosevic

I believe this happens here:

`  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          LABELS: community`

**Comment by nvukobratTT** [comment]
> > Looks good, important part from my end is that we're also labeling community issues on GitHub, besides sending a message :))
> > I'll leave for more detailed overview to @vmilosevic
> 
> I believe this happens here:
> 
> ` GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} GH_REPO: ${{ github.repository }} LABELS: community`

Yup, my msg was just confirmation of it :)) Thanks for pushing this! This will be great!

**Review by vmilosevic — APPROVED** [review]
Looks good

**Pull request merged**
