### PR TITLE
tt-mlir uplift week 38

### PR DESCRIPTION
**Pull request by vmilosevic**
Update mlir to latest main

### CODE REVIEW

**Comment by nvukobratTT** [comment]
Does it make sense to start with week 0?

**Comment by vmilosevic** [comment]
> Does it make sense to start with week 0?

week38 is a calendar week from the beginning of the year

**Comment by nvukobratTT** [comment]
Looks like dual conv2d fails during runtime:
```
...
2024-09-18 09:09:45.831 | INFO     | forge.compiled_graph_state:__call__:330 - Running model DualConv2d on device...
                 Always | FATAL    | Unsupported data type
terminate called after throwing an instance of 'std::runtime_error'
                  Metal | INFO     | Closing device 0
                  Metal | INFO     | Closing device 0
  what():  TT_THROW @ /__w/tt-forge-fe/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/tensor/tensor_impl.cpp:42: tt::exception
info:
Unsupported data type
backtrace:
 --- tt::tt_metal::tensor_impl::element_size_bytes(tt::tt_metal::DataType)
 --- tt::tt_metal::create_device_tensor(tt::tt_metal::Shape const&, tt::tt_metal::DataType, tt::tt_metal::Layout, tt::tt_metal::Device*, tt::tt_metal::MemoryConfig const&)
...
```

@pilkicTT do you happen to have some context around this failure? It fails on one of the conv tests. @vmilosevic did the pipeline fail on the same test after the re-run?

**Comment by vmilosevic** [comment]
Reset uplift to use latest tt-mlir origin/main

**Comment by vmilosevic** [comment]
@nvukobratTT we can still see errors in tests,

```
2024-09-20 09:31:34.162 | FATAL    | TTDevice        - Tensor 1 - data type mismatch: expected Float32, got BFloat16

2024-09-20 09:36:27.500 | ERROR    | Always          - Unsupported operation for lowering from TTForge to TTIR: pad_tile
<s>Q: What is the largest animal?
A: The blue whale.
Q: What is the largest animal?
A: The blue whale. It is the largest animal on Earth. It is also the

```

Did this pass when tested locally?

**Comment by nvukobratTT** [comment]
> @nvukobratTT we can still see errors in tests,
> 
> ```
> 2024-09-20 09:31:34.162 | FATAL    | TTDevice        - Tensor 1 - data type mismatch: expected Float32, got BFloat16
> 
> 2024-09-20 09:36:27.500 | ERROR    | Always          - Unsupported operation for lowering from TTForge to TTIR: pad_tile
> <s>Q: What is the largest animal?
> A: The blue whale.
> Q: What is the largest animal?
> A: The blue whale. It is the largest animal on Earth. It is also the
> ```
> 
> Do you know if this passed when tested locally?

First of all, seems like the previous blocker was fixed (async-related issues). 

Secondly, as you mentioned these issues are still there (as expected) + we have a new set of issues on our end. We'll have to determine from where these issue are coming. 

I'll find someone to take a look root cause of these issues first, and than we can proceed with making appropriate fix on both MLIR and FFE.

**Comment by nvukobratTT** [comment]
Going back to my message above, Deepak will bisect these error groups and figure out which specific comments from MLIR caused each type of regression. Once we get that information, we can open up set of issues on FFE and MLIR to patch each failing scenario.

**Comment by dgolubovicTT** [comment]
This error related to pad_tile exists on forge main, so it has nothing to do with mlir bringup. The test is marked by xfail on main.

**Comment by vmilosevic** [comment]
@nvukobratTT all looks good, I'll close this PR in favor of https://github.com/tenstorrent/tt-forge-fe/pull/340

**Comment by vmilosevic** [comment]
Closing this PR in favor of https://github.com/tenstorrent/tt-forge-fe/pull/340

**Pull request closed without merging**
